Material/Sitepoint-source-master/Feeds_with_Stream/config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:new, :create]

  resources :pins, only: [:create, :destroy]

  resources :users, only: [:index]
  devise_for :users

  resources :follows, only: [:create, :destroy]

  scope path: '/feeds', controller: :feeds, as: 'feed' do
    get 'user/:id', to: :user, as: :user
    get 'flat', to: :flat
    get 'notification', to: :notification
    get 'aggregated', to: :aggregated
  end

  root to: 'pages#index'

end

Material/Sitepoint-source-master/Feeds_with_Stream/app/models/follow.rb
# == Schema Information
#
# Table name: follows
#
#  id         :integer          not null, primary key
#  target_id  :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :target, class_name: "User"

  validates :target_id, presence: true
  validates :user_id, presence: true

  include StreamRails::Activity
  as_activity

  def activity_notify
    [StreamRails.feed_manager.get_notification_feed(self.target_id)]
  end

  def activity_object
    self.target
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  message    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Item < ActiveRecord::Base
  has_many :pins
  belongs_to :user

  def user_pin(user = nil)
    self.pins.where(user: user).first
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/models/pin.rb
# == Schema Information
#
# Table name: pins
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  influencer_id :integer
#  item_id       :integer
#  message       :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :item

  validates :item, presence: true, uniqueness: {scope: :user}
  validates :user, presence: true, uniqueness: {scope: :item}

  include StreamRails::Activity
  as_activity

  def activity_object
    self.item
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :follows
  has_many :items

  def followed_by(user = nil)
    user.follows.find_by(target_id: id)
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!
  before_action :create_enricher

  def user
    @user = User.find(params[:id])
    feed = StreamRails.feed_manager.get_user_feed(@user.id)
    results = feed.get['results']
    @activities = @enricher.enrich_activities(results)
  end

  def flat
    feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:flat]
    results = feed.get['results']
    @activities = @enricher.enrich_activities(results)
  end

  def aggregated
    feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:aggregated]
    results = feed.get['results']
    @activities = @enricher.enrich_aggregated_activities(results)
  end

  def notification
    feed = StreamRails.feed_manager.get_notification_feed(current_user.id)
    results = feed.get['results']
    @activities = @enricher.enrich_aggregated_activities(results)
  end

  private

  def create_enricher
    @enricher = StreamRails::Enrich.new
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    follow = Follow.new(follow_params)
    follow.user = current_user
    if follow.save
      StreamRails.feed_manager.follow_user(follow.user_id, follow.target_id)
    end
    flash[:success] = 'Followed!'
    redirect_to users_path
  end

  def destroy
    follow = Follow.find(params[:id])
    if follow.user_id == current_user.id
      follow.destroy!
      StreamRails.feed_manager.unfollow_user(follow.user_id, follow.target_id)
    end
    flash[:success] = 'Unfollowed!'
    redirect_to users_path
  end

  private

  def follow_params
    params.require(:follow).permit(:target_id)
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    flash[:success] = "Item created!"
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:message, :title)
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.order('created_at DESC')
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!

  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user
    @pin.save!
    flash[:success] = "Pinned!"
    redirect_to root_path
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    flash[:success] = "Unpinned!"
    redirect_to root_path
  end

  private

  def pin_params
    params.require(:pin).permit(:item_id)
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

Material/Sitepoint-source-master/Feeds_with_Stream/app/views/aggregated_activity/_follow.html.erb
<i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago

<% for activity in activity['activities'] %>
  <%= render_activity activity %>
<% end %>

Material/Sitepoint-source-master/Feeds_with_Stream/app/views/aggregated_activity/_pin.html.erb
<% if activity['actor_count'] == 1 %>
  <%= activity['activities'][0]['actor'].name %> pinned <%= pluralize(activity['activity_count'], 'item') %>
<% elsif activity['actor_count'] == 2 %>
  <%= activity['activities'][0]['actor'].name %> and <%= activity['activities'][1]['actor'].name %> pinned <%= activity['activity_count'] %> items
<% else %>
  <%= activity['activities'][0]['actor'].name %>, <%= activity['activities'][1]['actor'].name %> and <%= activity['actor_count'].name - 2 %> more pinned <%= activity['activity_count'] %> items
<% end %>

<div class="pull-right">
  <i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago
</div>

<% for activity in activity['activities'] %>
  <%= render_activity activity %>
<% end %>

Material/Sitepoint-source-master/Feeds_with_Stream/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>FeedMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'FeedMe', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'New item', new_item_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Flat news feed', feed_flat_path %></li>
          <li><%= link_to 'Aggregated news feed', feed_aggregated_path %></li>
          <li><%= link_to 'Notification feed', feed_notification_path %></li>
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="glyphicon"></i> <%= current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My feed', feed_user_path(current_user) %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>

  <div id="footer">
    <div class="container-fluid">
      <p class="text-muted">Created by <a href="http://bodrovis.tech" target="_blank">Radiant Wind</a></p>
    </div>
  </div>
</div>

</body>
</html>